from selenium.webdriver.common.by import By


class Locators():
    # login page
    USERNAME = (By.ID, "username")
    PASSWORD = (By.ID, "password")
    LOGIN_BUTTON = (By.ID, "kc-login")

    # common navigation
    TOAST_MESSAGE = (By.XPATH, "//div[@class = 'Toastify__toast-body']/div")
    NEW_SEARCH_NAV = (By.XPATH, "//a[@aria-label='navigate-to-search']")
    NEW_SEARCH_MENU = (By.XPATH, "//span[contains(text(),'New Search')]")
    SHORTLIST_MENU = (By.XPATH, "//span[contains(.,'Shortlists')]")

    # search page
    MATCH_INPUT = (By.ID, "match-text-input")
    CLEAR_MATCH_INPUT = (By.XPATH, "//button[@aria-label='clear-match-text']")
    FIND_MATCH_BUTTON = (By.ID, "find-a-match")
    FILTER_KEYWORD_SECTION = (By.ID, "filter-keyword")
    FILTER_KEYWORD_INPUT = (By.ID, "filter-keyword-multi-input")
    FILTER_EDUCATION_SECTION = (By.ID, "filter-education")
    FILTER_EDUCATION_INPUT = (By.ID, "filter-education-multi-input")
    FILTER_EDUCATION_EXPAND_FILTERS = (By.XPATH, "//div[@id='filter-education-content']//div[@role='button']")
    FILTER_EDUCATION_INSTITUTION = (By.XPATH, "//li[@data-value='education.institution']")
    FILTER_EMPLOYMENT_SECTION = (By.ID, "filter-employment")
    FILTER_EMPLOYMENT_INPUT = (By.ID, "filter-employment-multi-input")
    FILTER_EMPLOYMENT_EXPAND_FILTERS = (By.XPATH, "//div[@id='filter-employment-content']//div[@role='button']")
    FILTER_EMPLOYMENT_INSTITUTION = (By.XPATH, "//li[@data-value='experience.company']")
    BYEBIAS_TOGGLE = (By.XPATH, "//span[contains(text(),'ByeBias')]")
    ADD_TO_SHORTLIST_ICON = (By.ID, "add-to-shortlist")
    CREATE_NEW_SHORTLIST_SECTION = (By.XPATH, "//div[@aria-label='add-to-new-shortlist-step-1']")
    CREATE_NEW_SHORTLIST_NAME_INPUT = (By.XPATH, "//input[@aria-label='new-shortlist-name']")
    CREATE_NEW_SHORTLIST_ADD_BUTTON = (By.XPATH, "//span[@aria-label='create-new-shortlist']")
    CREATE_NEW_SHORTLIST_NOTIFICATION = (By.XPATH, "//div[@aria-label='add-to-new-shortlist-step-3']/span")
    HIDE_TALENT_BUTTON = (By.XPATH, "(//button[@aria-label='hide-talent'])[1]")
    NEXT_PAGE_BUTTON = (By.XPATH, "(//button[@aria-label='next-page'])[1]")
    TALENTS_PER_PAGE_TEXT = (By.XPATH, "//button[@aria-label='next-page']/preceding-sibling::span")
    NO_TALENTS_MESSAGE_TEXT = (By.XPATH, "//span[contains(.,'No talent matches your search criteria.')]")
    TALENT_CARD = (By.ID, "talent-card-content")
    FIRST_TALENT_NAME = (By.XPATH, "(//div[@id='talent-card-content']//a[@aria-label='full-profile-link']/preceding-sibling::span[contains(@class,'MuiTypography-smallHeadline')])[1]")
    FIRST_TALENT_PROFILE_IMG = (By.XPATH, "(//a[@aria-label='nova-talent-avatar']/img)[1]")
    OPEN_TALENT_FULL_PROFILE_IN_NEW_TAB_BUTTON = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[3]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[4]/a[1]/span[1]")
    TALENT_PROFILE_READ_MORE_BUTTON = (By.XPATH, "//span[contains(text(),'Read More')]")

    # shortlist page
    SHORTLIST_NAME_INPUT = (By.XPATH, "//*[@aria-label='shortlist-name-input']//input")
    CREATE_SHORTLIST_BTN = (By.XPATH, "//button[@aria-label='create-shortlist-button']")
    DELETE_SHORTLIST_BTN = (By.XPATH, "//button[@aria-label='delete-shortlist-button']")
    DELETE_SHORTLIST_YES_BTN = (By.XPATH, "//button[text()='Yes']")
    EDIT_SHORTLIST_BTN = (By.XPATH, "//button[@aria-label='edit-shortlist-button']")
    SAVE_SHORT_LIST_BTN = (By.XPATH, "//button[@aria-label='save-edit-button']")
    CANCEL_SHORTLIST_BTN = (By.XPATH, "//button[@aria-label='cancel-edit-button']")
    REMOVE_TALENT_FROM_SHORTLIST_BTN = (By.XPATH, "//button[@aria-label='remove-talent-button']")
    SHORTLIST_BY_NAME = (By.XPATH, "(//a//span[contains(text(),'{0}')])[1]")
    SHORTLIST_LINK = (By.XPATH, "(//a[contains(@aria-label,'shortlist-link')])[1]")
    NO_SHORTLISTS_MESSAGE = (By.XPATH, "//span[text()='Begin a search, or create a shortlist to get started.']")
    NO_TALENTS_IN_SHORTLIST_MESSAGE = (By.XPATH, "//span[text()='This shortlist has no prospects in it.']")
    SHORTLISTS_BUTTON = (By.XPATH, "//span[contains(text(),'Shortlists')]")
    EXPAND_TALENT_FULL_PROFILE = (By.XPATH, "//span[contains(text(),'Expand')]")
    OPEN_IN_NEW_TAB = (By.XPATH, "//span[contains(text(),'Open In New Tab')]")
    READ_MORE = (By.XPATH, "//*[@id='root'']/div/div[2]/div/div/div[2]/div[1]/ul[1]/li[4]/div[2]/div[2]/button/span[1]")

    # users page
    USERS_NEXT_PAGE_BUTTON = (By.XPATH, "//button[@aria-label='Go to next page']")
    USERS_PER_PAGE = (By.CSS_SELECTOR, ".MuiTablePagination-displayedRows")
    CREATE_USER_BUTTON = (By.XPATH, "//button/span[text()='Create New User']")
    SUBMIT_CREATE_USER_BUTTON = (By.XPATH, "//button[@aria-label='create new user']")
    SELECT_USER_TYPE_BUTTON = (By.ID, "modal-user-type-select")
    USER_TYPE_USER_OPTION = (By.XPATH, "//li[text()='User']")
    USERNAME_INPUT = (By.ID, "username")
    EMAIL_INPUT = (By.ID, "email")
    FIRST_NAME_INPUT = (By.ID, "firstName")
    LAST_NAME_INPUT = (By.ID, "lastName")
    PASSWORD_INPUT = (By.ID, "password")
    ORGANISATION_COMBOBOX = (By.XPATH, "//input[@role='combobox']")    # Create users page
    USER_ADMIN_TOGGLE_SWITCH = (By.XPATH, "//input[@type = 'checkbox']")
    CREATE_NEW_USER_ALERT = (By.XPATH, "//div[@role='alert' and contains(div/text(), 'Created Successfully')]/div")
    DIALOG_WINDOW_TITLE = (By.XPATH, "//h2[contains(@class, 'MuiDialogTitle-root')]")
    DIALOG_WINDOW_CLOSE_BUTTON = (By.XPATH, "//button[@aria-label='close']")

    # organizations page
    CREATE_NEW_ORG_BUTTON = (By.XPATH, "//button/span[text()='Create New Organization']")
    ORG_NAME_INPUT = (By.ID, "orgName")
    NUMBER_OF_CONTACTS_INPUT = (By.ID, "lookupTokens")
    SUBMIT_BUTTON_NEW_ORG = (By.XPATH, "//button[@aria-label='create new organization']")
    ORG_NAME_INPUT_VALIDATION = (By.ID, "orgName-helper-text")
    NUMBER_OF_CONTACTS_INPUT_VALIDATION = (By.ID, "lookupTokens-helper-text")
    ASSERT_ORG_ALREADY_EXIST = (By.XPATH, "//p[contains(@class,'MuiDialogContentText-root')]")

    # User settings page
    ADD_NEW_SCHEDULE_BUTTON = (By.XPATH,"//button[@aria-label='add-scheduling-page']")
    SCHEDULE_NAME_INPUT = (By.XPATH,"//input[@aria-label='schedule-name']")
    SCHEDULE_LOCATION_INPUT = (By.XPATH, "//input[@aria-label='schedule-location']")
    SAVE_SCHEDULE_BUTTON = (By.XPATH,"//button[@aria-label='contact-dialog-confirm']")
    EDIT_SCHEDULE_BUTTON = (By.XPATH,"//button[@aria-label='edit-schedule']")
    DELETE_SCHEDULE_BUTTON = (By.XPATH,"//button[@aria-label='contact-dialog-delete-schedule']")
    TALENT_EMAIL_BUTTON = (By.XPATH, "//button[@aria-label='compose-email-62d5dfd2978d99d63bc133a3']")
    LOOKUP_TOKEN_CONFIRM_BUTTON = (By.XPATH, "//button[@aria-label='token-dialog-confirm']")
    EMAIL_SUBJECT_FIELD = (By.XPATH,"//input[@aria-label='email-compose-subject-input']")
    EMAIL_BODY = (By.XPATH,"//div[@aria-label='email-compose-message-input']")
    EMAIL_SEND_BUTTON = (By.XPATH, "//button[@aria-label='compose-email-send-button']")
    EMAIL_PERSONALIZED_GREETING = (By.XPATH, "//input[@aria-label='email-compose-personalized-greeting-input']")
    EMAIL_SENT_CONFIRMED_ALERT = (By.XPATH, "//div[@role='alert' and contains(div/text(), 'Your Email Will Be Sent')]/div")
